### ISSUE TITLE
Data::Dump::Streamer should be listed as a prereq

### ISSUE THREAD

**Issue by wolfsage** [jrockway/anyevent-inotify-simple#3]
In the event of some failures, AnyEvent::INotify::SImple will `require Data::Dump::Streamer` to add diagnostics.

Therefore, `Data::Dump::Streamer` should be listed as a prereq, otherwise the diagnostic dumping will fail

**Comment by robn** [comment]
Use of Data::Dump::Streamer removed in edcfa588.
